# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
    ]
