# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0005_auto_20170426_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_finish',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
