# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0006_auto_20170426_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='user_id',
        ),
    ]
