# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0007_auto_20170427_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_finish',
            field=models.DateField(default=b'27.04.2017'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start',
            field=models.DateField(default=b'27.04.2017'),
        ),
    ]
