# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0008_auto_20170427_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_finish',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start',
            field=models.CharField(max_length=50),
        ),
    ]
