# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0009_auto_20170428_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ManyToManyField(related_name='user_trips', to='belt.User'),
        ),
    ]
