# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0012_auto_20170428_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start',
            field=models.DateField(),
        ),
    ]
